### ISSUE TITLE
New categories: Open Source Firmware and Open Source Hardware

### ISSUE THREAD

**Issue by FilipParyz** [yaph/awesome-it-merchandise#10]
I'd love to add to Open Source Firmware and Hardware projects.
Current categories won't fit the store I want to add.

**Comment by FilipParyz** [comment]
Actually, since firmware and hardware often go well together, maybe let's add a category that combines those, like "Open Source Firmware/Hardware" 👍

**Comment by yaph** [comment]
I'm fine with adding a "Open Source Firmware/Hardware" section. I like to keep alphabetical order for sections too so it should go before "Open Source Software". Thanks for the suggestion.
